#!/bin/bash

cd ${OPENSHIFT_JETTY8_DIR}/versions/8.14/

CMD="java -Xms384m -Xmx412m -jar start.jar -Djetty.host=$OPENSHIFT_JETTY8_APP_HOST -Djetty.port=$OPENSHIFT_JETTY8_APP_PORT"

nohup $CMD > $OPENSHIFT_JETTY8_LOG_DIR/server.log 2>&1 &

echo $! > jetty.pid


